# Provides all dependent services

version: '3.6'

services:
  mariadb:
    image: mariadb:10.4.12
    volumes:
      - nmsdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nms
      MYSQL_USER: nms
      MYSQL_PASSWORD: password
    #restart: on-failure
    healthcheck:
      test: mysqladmin ping -p12345

  nginx-proxy:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/docker_ssl_proxy:/etc/nginx/conf.d
    depends_on:
      - magmalte

  magmalte:
    build:
      context: ../..
      dockerfile: packages/magmalte/Dockerfile
    command: "/usr/local/bin/wait-for-it.sh -s -t 30 mariadb:3306 -- yarn run start:dev"
    volumes:
      - ../../packages/fbcnms-magma-api:/usr/src/packages/fbcnms-magma-api
      - ../../packages/magmalte/app:/usr/src/packages/magmalte/app
      - ../../packages/magmalte/scripts:/usr/src/packages/magmalte/scripts
      - ../../packages/magmalte/server:/usr/src/packages/magmalte/server
      - ../../packages/magmalte/grafana:/usr/src/packages/magmalte/grafana
      - ../../packages/magmalte/alerts:/usr/src/packages/magmalte/alerts
    depends_on:
      - mariadb
    networks:
      - default
      - orc8r_default
    ports:
      - "8081:8081"
    environment:
      API_CERT_FILENAME: /run/secrets/api_cert
      API_PRIVATE_KEY_FILENAME: /run/secrets/api_key
      API_HOST: ${API_HOST:-nginx:9443}
      PORT: 8081
      HOST: 0.0.0.0
      MYSQL_HOST: mariadb
      MYSQL_DB: nms
      MYSQL_USER: nms
      MYSQL_PASS: password
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN:-}
      MYSQL_DIALECT: mariadb
      ADDITIONAL_PROVISION_FILE_PAYLOAD_FILENAME: ${ADDITIONAL_PROVISION_FILE_PAYLOAD_FILENAME}
      PROVISION_FILE_SIGNATURE_PASSPHRASE: ${PROVISION_FILE_SIGNATURE_PASSPHRASE}
      # Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
      PUPPETEER_SKIP_DOWNLOAD: "true"
    healthcheck:
      test: curl -If localhost:8081/healthz
    restart: on-failure
    secrets:
      - api_cert
      - api_key

secrets:
  api_cert:
    file: ${API_CERT_FILENAME:-../../../../.cache/test_certs/admin_operator.pem}
  api_key:
    file: ${API_PRIVATE_KEY_FILENAME:-../../../../.cache/test_certs/admin_operator.key.pem}

networks:
  orc8r_default:
    external: true

volumes:
  nmsdb:
